import {extractAffiliateUrl,validateAffiliateUrl} from "/scripts/affiliate-url.mjs";
const isPreview=new URLSearchParams(location.search).get("preview")==="1";
if(isPreview){document.querySelector("#gate").hidden=true;document.querySelector("#console").hidden=false;init();}
const STORE="margin:affiliate-intake:v1";
const order=["dining-table-for-couples","lighting-for-couples","bed-mattress-for-couples","rug-for-couples"];
const labels={"dining-table-for-couples":"Dining","lighting-for-couples":"Lighting","bed-mattress-for-couples":"Bedroom","rug-for-couples":"Textile"};
let products=[],sources=new Map(),values={},results={};
async function init(){
  const [catalog,registry]=await Promise.all([fetch("/data/article-products.json").then(r=>r.json()),fetch("/data/article-sources.json").then(r=>r.json())]);
  products=catalog.products.filter(p=>order.includes(p.articleId));sources=new Map(registry.sources.map(s=>[s.id,s]));
  try{values=JSON.parse(localStorage.getItem(STORE)||"{}")}catch{values={}}
  render();bind();
  const target=new URLSearchParams(location.search).get("article");if(target)document.getElementById(target)?.scrollIntoView();
}
const money=v=>v?`¥${Number(v).toLocaleString("ja-JP")}`:"再確認待ち";
function checkAll(){
  results={};const used=new Map();
  for(const p of products){const raw=values[p.id]||"";if(!raw){results[p.id]={valid:false,code:"empty",message:"未入力",value:""};continue;}const r=validateAffiliateUrl(raw,p.official_url);results[p.id]=r;if(r.valid){if(used.has(r.value)){results[p.id]={...r,valid:false,code:"duplicate",message:`同じリンクが ${used.get(r.value)} に入力されています`};results[used.get(r.value)]={...results[used.get(r.value)],valid:false,code:"duplicate",message:"同じAffiliate URLが複数商品に入力されています"};}else used.set(r.value,p.id);}}
}
function status(count,total,hasInvalid){if(count===0)return"Not started";if(hasInvalid)return"In progress";if(count===total)return"Ready to export";return"In progress";}
function render(){checkAll();const root=document.querySelector("#articles");root.innerHTML=order.map(articleId=>articleMarkup(articleId)).join("");updateOverall();}
function articleMarkup(articleId){const list=products.filter(p=>p.articleId===articleId),valid=list.filter(p=>results[p.id].valid).length,invalid=list.some(p=>values[p.id]&&!results[p.id].valid);return `<section class="article" id="${articleId}"><div class="article-head"><div><p class="eyebrow">ARTICLE / ${list[0]?.articleId||""}</p><h2>${labels[articleId]}</h2><a class="official" href="/articles/${articleId}/?preview=1">記事Previewへ戻る →</a></div><div class="progress"><strong>${valid} / ${list.length} links completed</strong><br><span>${status(valid,list.length,invalid)}</span><div class="actions"><button data-export="${articleId}">Partial Export</button><button data-clear="${articleId}" class="quiet">Clear article</button></div></div></div>${list.map(productMarkup).join("")}</section>`;}
function productMarkup(p){const r=results[p.id],source=sources.get(p.source_id);return `<article class="product" data-product="${p.id}"><div><p class="meta">${labels[p.articleId]} · ${p.selection_role}</p><h3><small>${p.brand}</small>${p.name}</h3><p class="meta">${p.id}</p><dl class="facts"><dt>Price</dt><dd>${money(p.price)}</dd><dt>Shipping</dt><dd>${p.shipping}</dd><dt>Review</dt><dd>${p.review||"未集計・再確認待ち"}</dd><dt>Source</dt><dd>${source?`確認 ${source.last_verified} / 再確認必須`:"Registry missing"}</dd></dl><a class="official" href="${p.official_url}" target="_blank" rel="noopener">楽天商品ページを開く ↗</a></div><div class="field"><label for="url-${p.id}">AFFILIATE URL</label><textarea id="url-${p.id}" data-id="${p.id}" spellcheck="false" autocomplete="off" placeholder="https://hb.afl.rakuten.co.jp/…">${escapeHtml(values[p.id]||"")}</textarea><div class="feedback"><span class="${r.valid?'valid':values[p.id]?'invalid':''}">${r.message}</span><span>${r.valid?'Registered':values[p.id]?'Error':'Not started'}</span></div></div></article>`;}
const escapeHtml=s=>String(s).replace(/[&<>\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
function bind(){
  document.addEventListener("input",e=>{if(e.target.matches("textarea[data-id]")){const clean=extractAffiliateUrl(e.target.value);values[e.target.dataset.id]=clean;localStorage.setItem(STORE,JSON.stringify(values));checkAll();refreshFields();updateOverall();}if(e.target.id==="incomplete")updateOverall();});
  document.addEventListener("click",e=>{const article=e.target.dataset.clear||e.target.dataset.export;if(e.target.dataset.clear){if(confirm(`${labels[article]} の入力を消去しますか？`)){products.filter(p=>p.articleId===article).forEach(p=>delete values[p.id]);save("Article cleared");}}else if(e.target.dataset.export)exportJson(article);});
  document.querySelector("#save").onclick=()=>save("Saved locally");document.querySelector("#clearAll").onclick=()=>{if(confirm("40商品の一時入力をすべて消去しますか？")){values={};save("All cleared")}};
  document.querySelector("#exportJson").onclick=()=>exportJson();document.querySelector("#exportMessage").onclick=copyMessage;
}
function refreshFields(){for(const p of products){const card=document.querySelector(`[data-product="${p.id}"]`),r=results[p.id];if(!card)continue;const spans=card.querySelectorAll(".feedback span");spans[0].className=r.valid?"valid":values[p.id]?"invalid":"";spans[0].textContent=r.message;spans[1].textContent=r.valid?"Registered":values[p.id]?"Error":"Not started";}}
function updateOverall(){const complete=products.filter(p=>results[p.id].valid).length,invalid=products.some(p=>values[p.id]&&!results[p.id].valid);document.querySelector("#overall").textContent=`${complete} / ${products.length} links completed`;document.querySelector("#overallStatus").textContent=complete===products.length&&!invalid?"Complete":status(complete,products.length,invalid);document.querySelector("#exportJson").disabled=invalid;const only=document.querySelector("#incomplete")?.checked;document.querySelectorAll(".product").forEach(el=>{if(only)el.hidden=results[el.dataset.product].valid});}
function save(message){localStorage.setItem(STORE,JSON.stringify(values));document.querySelector("#notice").textContent=message;render();}
function itemsFor(articleId){return products.filter(p=>(!articleId||p.articleId===articleId)&&results[p.id].valid).map(p=>({productId:p.id,officialUrl:p.official_url,affiliateUrl:results[p.id].value}));}
function exportJson(articleId){const scoped=products.filter(p=>!articleId||p.articleId===articleId);if(scoped.some(p=>values[p.id]&&!results[p.id].valid)){return notice("不正なリンクを修正してからExportしてください");}const items=itemsFor(articleId);if(!items.length)return notice("Exportできる有効なリンクがありません");const blob=new Blob([JSON.stringify({generatedAt:new Date().toISOString(),items},null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="affiliate-links-import.json";a.click();URL.revokeObjectURL(a.href);notice(`${items.length}件をExportしました`);}
async function copyMessage(){const items=itemsFor();if(!items.length)return notice("コピーできる有効なリンクがありません");const lines=["Phase 9.2として以下のAffiliate URLを登録してください。",""];for(const item of items){const p=products.find(x=>x.id===item.productId);lines.push(`商品ID：${p.id}`,`商品名：${p.brand} ${p.name}`,`official_url：${p.official_url}`,`affiliate_url：${item.affiliateUrl}`,"");}lines.push("実施内容：","- 対応Product Libraryへ登録","- publishable判定","- Source Registry再確認","- Product Validation","- Article Validation","- Preview確認","- Production公開条件確認","- mainへマージしない","- Draft PR #2へ追加コミット");await navigator.clipboard.writeText(lines.join("\n"));notice(`${items.length}件のCodex Messageをコピーしました`);}
const notice=message=>document.querySelector("#notice").textContent=message;
